services:
  dev_env:
    image: node:current-alpine
    working_dir: /usr/src/app
    expose:
      - 3001
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app/
    command: >
      sh -c "yarn install && yarn dev"
